version: "3.9"
services:
  itchysats-mainnet:
    image: ghcr.io/itchysats/itchysats/taker:0.4.21
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
    command: |
      --log-level=Info
      mainnet
