version: "3"
services:
  itchysats-testnet:
    image: ghcr.io/itchysats/itchysats/taker:0.6.1
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
    command: |
      --log-level=Info
      testnet
